### ISSUE TITLE
Support dynamically increasing batch sizes

### ISSUE THREAD

**Issue by githubnemo** [dnouri/skorch#109]
If we want to support mechanisms like the one described [here](https://arxiv.org/abs/1711.00489) that do batch size re-scaling instead of learn-rate annealing, we probably have to do changes to support this as we only initialize the `DataLoader` once with the batch-size.

So, two questions:

- [ ] is this already supported by skorch?
- [ ] what changes have to be done?

**Comment by benjamin-work** [comment]
Since the iterator (which is responsible for batching) is fetched at the beginning of each epoch, I don't see why it shouldn't be possible. A callback that sets the batch size after each epoch should be sufficient. I haven't looked at the details or tried it, but I would tentatively say:

- [x] this is already supported by skorch?

Another question is whether the dataset should be fetched once for each epoch or once for each fit call (status quo). In case you need the former, a workaround would be:

```
net = NeuralNet(..., max_epochs=1)
for epoch in range(num_epochs):
    net.partial_fit(X, y)
    net.set_params(datast__foo=func(epoch))
```
