### ISSUE TITLE
torch.log in NeuralNetClassifier.get_loss 

### ISSUE THREAD

**Issue by windj007** [dnouri/skorch#136]
Hi!

Neural network output passed to torch.log in https://github.com/dnouri/skorch/blob/master/skorch/net.py#L1153

Two problems with that:
1) It's not recommended to use nll_loss(log(softmax())) due to poor performance and numerical stability, according to note here: http://pytorch.org/docs/0.3.0/nn.html#torch.nn.functional.softmax
2) This torch.log is implicit - it's never mentioned anywhere in documentation. It took me the about a half of a day to figure out why I get y_pred=nan in loss. I came from plain pytorch background, so I had log_softmax at the output of my network.

May be it's better to remove this torch.log or add some remarks to the docs?

Thank you.

**Comment by BenjaminBossan** [comment]
I'm sorry to hear that this caused you some lost time. The documentation does say that it expects softmax output ([see here](https://skorch.readthedocs.io/en/latest/user/neuralnet.html#module): _"...if you have a classification task, you should make sure that the final output nonlinearity is a softmax"_; it is also mentioned in the [Basic_Usage notebook](http://nbviewer.jupyter.org/github/dnouri/skorch/blob/master/notebooks/Basic_Usage.ipynb#Definition-of-the-pytorch-classification-module)). Can you tell us where you looked so that we can improve the docs?

The problem with removing the implicit *log* is that we would then need to call an implicit *exp* in the `predict_proba` call to make it sklearn compliant, so it's either here or there. In addition, AFAIK, most other frameworks (say keras) also expect softmax nonlinearity as the final output for classification tasks -- it's just more intuitive overall.

Nonetheless, because of the pytorch issue you mentioned, we should think about a change here. I don't know whether using softmax is that big of an issue overall (in terms of performance and stability), do you know of a benchmark that illuminates this?

Apart from that, I could see us implementing a check on the module output to prevent errors such as the one you encountered, although we would lose some performance as a consequence.

**Comment by loic001** [comment]
Hi,

`y_pred_log = torch.log(y_pred)`

if y_pred contains exact "0.0" values, output of torch.log will contains "inf" values.

Please correct me if i'm wrong, but I think it's a big problem because the loss could explode and result to NaN values...

**Comment by githubnemo** [comment]
> if `y_pred` contains exact "0.0" values, output of `torch.log` will contains `inf` values.

Yes, this can happen for big inputs, for example:
```
>>> torch.log(torch.nn.functional.softmax(torch.Tensor([1e5,0])))
Variable containing:
  0
-inf
[torch.FloatTensor of size 2]
```

whereas `log_softmax` handles this well:
```
>>> torch.nn.functional.log_softmax(torch.Tensor([1e5,0]))
Variable containing:
 0.0000e+00
-1.0000e+05
[torch.FloatTensor of size 2]
```

We should definitely consider this.

**Comment by benjamin-work** [comment]
> Yes, this can happen for big inputs, for example:

I see, but in that case, you're probably already in trouble.

@loic001 If you have problems with softmax + log, use `NeuralNet` (not `NeuralNetClassifer`), which does not use the implicit log.

**Comment by timothygebhard** [comment]
Does using the log here even make sense for other loss functions than `NLLLoss`? For example, trying to use `BCELoss` gives me errors because of this:
```
RuntimeError: Assertion `x >= 0. && x <= 1.' failed.
```
Since `NeuralNetClassifier` explicitly allows to specify a `criterion`, I think there should be no hard-coded assumptions about the criterion (like "we have to take the log of the network outputs") in the `get_loss` method. I would therefore leave it to people that want to use `NLLLoss` to make sure they properly logarithmize their network predictions.

**Comment by ottonemo** [comment]
Excellent points.

The current state is that we override `get_loss` in `NeuralNetClassifier` to take the logarithm of the predictions so the default classification criterion `NLLLoss` works. The benefit of this is that the model is built with the output prediction in mind and does not need to care about the specifics of the loss function, similar to existing frameworks. This also has the following potential drawbacks:

1. numerically unstable (see https://github.com/dnouri/skorch/issues/136#issuecomment-362110010)
2. does not work well with the `criterion` parameter
3. surprising: `NLLLoss` but no `LogSoftmax` at the end (breaks with community standard)

Let's see what we can do to address these points. We could change the class to expect log probabilities from the model which then violates the contract of `pred_proba` as it should return values in [0;1] which log probabilities violate. In essence, we would still need to overwrite a function (`pred_proba` instead of `get_loss`) to make this work. Which version is better is up to debate but in switching to overriding `pred_proba` (i.e. returning `exp(y_pred)`) would address (1) and (3).

To address (2) we would have to find a solution that supports all classification criteria supported by PyTorch (CE, BCE, {Multi,Soft}Margin, NLL, ...). I'm not sure if this is manageable without making too many restrictions and losing what this class was essentially about: an easy wrapper for standard classification models (usually optimizing NLL). It is a convenience class that doesn't add anything that wouldn't be possible with the much more flexible `NeuralNet` class and if you really want to stick with `NeuralNetClassifier` for a more complex use-case you can always overwrite `get_loss` yourself, e.g. to support `BCELoss`:

    def get_loss(self, y_pred, y_true, **kwargs):
        return self.criterion_(y_pred, y_true)

If it is too much hassle to use `NeuralNet` then we should work on making that more accessible instead of putting more functionality into `NeuralNetClassifier` I think.

**Comment by ottonemo** [comment]
Since #198 is merged, `torch.log()` is only applied to the prediction if the criterion is set to `NLLLoss`.
