### ISSUE TITLE
make it possible to fit with a Dataset instance

### ISSUE THREAD

**Issue by benjamin-work** [dnouri/skorch#146]
The idea is to allow something like this:

```
dataset = MyDataset(...)
net = NeuralNet(...)
net.fit(dataset)
```

This should allow to do things like loading the training data on the fly (when they don't fit memory, for instance).

Acceptance criteria:
* Make something like the [cifar tutorial](https://github.com/pytorch/tutorials/blob/master/beginner_source/blitz/cifar10_tutorial.py) work

Open questions:
* How to differentiate between train and valid data?
* Do we need a `dataset_train` and a `dataset_valid`?
* What to do with the `net.dataset` parameter?

**Comment by ottonemo** [comment]
> How to differentiate between train and valid data?
> Do we need a dataset_train and a dataset_valid?

There are many scenarios where a train and a test dataset is provided but no validation. So, initially I thought we need to be able to compute a validation split from the train dataset, but for more complex splits (even a stratified split, really) this is impossible since we have no guarantee that we can inspect all targets from the dataset. Therefore, we cannot provide a functionality that computes a CV split from a given train dataset, we can only offer functionality to specify a separate validation dataset (this also means we raise an error if `X` is a dataset and the `train_split` is `CV`).

The current solution for this would look something like this:
```python
from skorch.helper import dataset_validation_split

net = Net(train_split=dataset_validation_split(validation_dataset))
net.fit(train_dataset)
```
with
```python
def dataset_validation_split(dataset_valid):
    def split(dataset_train, _):
        return dataset_train, dataset_valid, None, None
    return split
```

After that we can simply check in `fit_loop` whether `X_train` and `X_valid` are datasets and set `dataset_train` and `dataset_valid` accordingly.

> What to do with the `net.dataset` parameter?

Remove. Not needed since it can be substituted with a partial iterator anyway.

**Comment by ottonemo** [comment]
One thing we have to care about is that datasets encapsulate both X and y which makes them hard to use in callbacks that use the data supplied in each epoch (this data would be the dataset). Callbacks such as the epoch scoring callback would cease to function. This is OK since the user can always specify a custom scoring function that deals with datasets or use batch scoring but we should at least throw a meaningful exception in epoch scoring.
