### ISSUE TITLE
Is it really effective and efficient for finding best parameters of complicated CNN?

### ISSUE THREAD

**Issue by heroxx2011** [dnouri/skorch#164]
Hi,
I am training a complex architecture of CNN with Residual module, Inception module and so on. I want to know the skorch (maybe Grid Search) really effective and efficient for finding the best parameters of the network?

**Comment by ottonemo** [comment]
You can parametrize everything you want in your model and you can also swap out the model in a grid search if you like to. See the [documentation](http://skorch.readthedocs.io/en/latest/user/quickstart.html#grid-search) for a minimal example.

The [RNN sentiment classification example](https://github.com/dnouri/skorch/blob/master/examples/rnn_classifer/RNN_sentiment_classification.ipynb) is a bit more advanced where things like the number of layers, number of hidden units and the dropout factor are parametrized. You can potentially parametrize every aspect of your model.

If you use this feature you can test every relevant aspect of your model quite quickly. For early exploratory work I would recommend to use `RandomSearchCV` instead of `GridSearchCV` though.
