### ISSUE TITLE
Is skorch.Dataset needed?

### ISSUE THREAD

**Issue by taketwo** [dnouri/skorch#222]
I have several questions regarding skorch `Dataset`.

First, the documentation says:

> However, the Datasets provided by PyTorch are not sufficient for our usecase; for instance, they don’t work with numpy arrays.

As far as I can tell, this is no longer the case. A [commit](https://github.com/pytorch/pytorch/commit/7ea6ae57c84cdd72271381e42e7d2429f3f5527d) introducing numpy array support landed in PyTorch master more than a year ago, and the code has matured since then (see it's [current state](https://github.com/pytorch/pytorch/blob/27ea7148fecb88657c57e6e2f2b8d355d5d3ad78/torch/utils/data/dataloader.py#L165-L176)).

Second:

> skorch Dataset must have a device argument, which determines whether the returned data should be transferred to a specific computation device

Why is this needed? Both [`NeuralNet.infer()`](https://github.com/dnouri/skorch/blob/735e02296f82c0c607d5905dd4882133d9143282/skorch/net.py#L807) and [`NeuralNet.get_loss()`](https://github.com/dnouri/skorch/blob/735e02296f82c0c607d5905dd4882133d9143282/skorch/net.py#L906) explicitly call `to_tensor()` to transfer input and target to `self.device`.

Third:

> Dataset applies a transform [...]. By default, it casts the data to a PyTorch Tensor and replaces y by a dummy variable in case it is None.

Again, the `default_collate` function of PyTorch already does this. However, it's true that it does not handle `None`.

With all of this in mind, I wonder if skorch Dataset is needed? If the ability to convert `None` to a dummy variable is the only value added, then maybe it's easier to just add this to PyTorch `Dataset` and drop skorch `Dataset`? As a PyTorch/Skorch beginner I should admit that despite detailed documentation, the existence of two is still confusing.

**Comment by BenjaminBossan** [comment]
You're making good points. If we had the choice to get rid of our custom `Dataset`, we would gladly take it, since our goal is to provide as little friction with PyTorch as possible.

That being said, there are still data types that we would like to support and that wouldn't work otherwise. For instance, we often have `X` as dictionaries or DataFrames. The *magic* is in the `multi_indexing` part. You are right that we should highlight this better in the docs.

Regarding the casting to tensor, we probably really don't need it anymore. This is a relic from the time when PyTorch had tensors and variables. I'll open an issue for that.

Finally, I think there is value in having a `transform` method on `Dataset` after all the business with indexing is done. This way, a user has a dedicated transform method (instead of having to deal with everything in `__getitem__`).

**Comment by taketwo** [comment]
> we often have X as dictionaries or DataFrames. 

PyTorch [handles dictionaries](https://github.com/pytorch/pytorch/blob/27ea7148fecb88657c57e6e2f2b8d355d5d3ad78/torch/utils/data/dataloader.py#L183-L184), right? There is definitely no branch for pandas, but again, if this is (one of the few) raison d'être for `Dataset`, wouldn't it be easier to merge this upstream?

**Comment by BenjaminBossan** [comment]
> PyTorch handles dictionaries, right

It's not about the `DataLoader`; none of PyTorch's `Dataset`s can deal with dictionaries, DataFrames or None.

> wouldn't it be easier to merge this upstream?

Ideally, yes, but I suspect that this isn't high on the priority list of the developers.

**Comment by taketwo** [comment]
> It's not about the `DataLoader`; none of PyTorch's `Datasets` can deal with dictionaries, DataFrames or None.

I do realize that the functionality to convert numpy arrays and dicts is in PyTorch `DataLoader`, not in `Dataset`. Perhaps I'm missing some important point, but I don't understand why would we want this conversions to be a part of the `Dataset` class given that the data are anyway passed through `DataLoader` before being consumed by the network.

**Comment by BenjaminBossan** [comment]
Say we have an X like this:

`X = {'key0': numpy_array0, 'key1': numpy_array1}`

At the critical point, `_DataLoaderIter` does [this]((https://github.com/pytorch/pytorch/blob/75cf0faf4cca86270d90f4a13aaa91499bc0bc94/torch/utils/data/dataloader.py#L314)):

`batch = self.collate_fn([self.dataset[i] for i in indices])`

This would raise a `KeyError` instead of indexing into the numpy arrays. I don't see how we can make this work except by having a custom `Dataset` that knows how to index into the values of the dictionary.

We're open to suggestions how to treat this differently. The tests for what we expect should work are there, if you find a better way, make a PR. But let me warn you, the `DataLoader` code is very messy :)

**Comment by taketwo** [comment]
Thanks for taking time to explain, now this makes sense.
