### ISSUE TITLE
initialize must be called before partial_fit calls

### ISSUE THREAD

**Issue by stsievert** [dnouri/skorch#328]
This can be trouble with cloning.

Example, with a `pytest.raises` to show where the error occurs:

``` python
import skorch
from skorch import NeuralNetClassifier
from torchvision.models import resnet18
from sklearn.base import clone
from sklearn.datasets import make_classification
import torch.nn as nn
import torch
import pytest


class Simple(nn.Module):
    def __init__(self, d=10):
        super().__init__()
        self.layer = nn.Sequential(nn.Linear(d, 2))

    def forward(self, x):
        return self.layer(x)


d = 20
X, y = make_classification(n_features=d, n_classes=2)
X = X.astype("float32")

m = Simple(d=d)
m1 = NeuralNetClassifier(m, batch_size=256, optimizer=torch.optim.Adam)
m1.partial_fit(X, y)
assert m1.initialized_

m2 = clone(m1)
m2.set_params(optimizer=torch.optim.SGD, optimizer__momentum=0.1)
assert m2.initialized_
with pytest.raises(AttributeError):
    m2.partial_fit(X, y)
m2.initialize()
m2.partial_fit(X, y)
```

I ran into this in https://github.com/mrocklin/dask-ml/pull/2, but had a hard time remembering exactly why I needed it when creating this example. Hopefully this uncovers the issue.

**Comment by benjamin-work** [comment]
Thank you for bringing this to our attention.

I replicated your example but found that the line `m2.set_params(optimizer=torch.optim.SGD, optimizer__momentum=0.1)` was unnecessary to trigger the error. Is there a particular reason why you added that line?

Regarding the problem, it seems that the callbacks are uninitialized after cloning. When I empty the `callbacks_` attribute, the fit works. Why that happens I haven't figured out yet. Possibly, this requires a deeper look at `clone` (using `deepcopy` works, for instance). I will dig deeper when I have more time.

Regarding the solution, just calling `initialize()` on each `partial_fit` is not possible. `initialize()` resets the module, which is exactly what we don't want when we call `partial_fit`. We maybe could call `initialize_callbacks()` only, but this will probably also not work because some callbacks may rely on keeping their states between `partial_fit`s.

PS: Our `partial_fit` differs semantically from sklearn's `partial_fit`, which always runs but one epoch. In skorch, `partial_fit` is the same as `fit` except that the network is not re-initialized. This difference was not by design but since it's very practical and for backwards compatibility reasons, we might keep it that way.

**Comment by benjamin-work** [comment]
@stsievert Could you please explain what your use case and expectation is? As far as I can tell, sklearn usually resets the estimator after `clone`. With skorch `NeuralNet` this is not the case but that usually doesn't matter because a subsequent `fit` call will reset the estimator by calling `initialize`. Therefore, `NeuralNet` works with grid search et al. as expected.

When you clone `NeuralNet`, its callbacks are initialized anew, like any sklearn estimator. Thus, when you call `partial_fit` which circumvents `initialize`, the callbacks are not "ready" and the error is raised. As said earlier, we could initialize the callbacks but depending on the use case, this may not be desired, hence my question.

**Comment by stsievert** [comment]
I'm closing this issue; all signs point to the issue I thought not being an issue (which is different than the issue I showed in the first post). In my actual application, removing the `initialize` call after clone appears to work.

Here's my actual use case:

``` python
import skorch
from skorch import NeuralNetClassifier, NeuralNetRegressor
from torchvision.models import resnet18
from sklearn.base import clone
from sklearn.datasets import make_classification
import torch.nn as nn
import torch
import pytest


class Simple(nn.Module):

    def __init__(self, d=10):
        super().__init__()
        self.layer = nn.Sequential(nn.Linear(d, 1))

    def forward(self, x):
        return self.layer(x)


class Net(NeuralNetRegressor):
    steps = 0

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Raises TypeError if other parameters set in __init__
        # (which is why `steps` is outside __init__)
        #  self.steps = 0

    def partial_fit(self, *args, **kwargs):
        self.steps += 1
        print("calling pf with steps =", self.steps)
        super().partial_fit(*args, **kwargs)

    def score(self, X, y):
        X = skorch.utils.to_tensor(X, device=self.device)
        y = skorch.utils.to_tensor(y, device=self.device)

        y_hat = self.predict(X)
        y_hat = skorch.utils.to_tensor(y_hat, device=self.device)
        loss = super().get_loss(y_hat, y, X=None, training=False).item()
        print(f"steps = {self.steps}, loss = {loss}")
        return -1 * loss


d = 20
X, y = make_classification(n_features=d, n_classes=2)
X = X.astype("float32")
y = y.astype("float32").reshape(-1, 1)

model = Simple(d=d)

m1 = Net(model, criterion=torch.nn.MSELoss, optimizer=torch.optim.Adam)

m2 = clone(m1).set_params(optimizer=torch.optim.SGD)
assert isinstance(m2.optimizer_, torch.optim.SGD)
m2.partial_fit(X, y)
m2.score(X, y)

m3 = clone(m1).set_params(optimizer=torch.optim.RMSprop)
assert isinstance(m3.optimizer_, torch.optim.RMSprop)
m3.partial_fit(X, y)
m3.score(X, y)
```
