### ISSUE TITLE
Thoughts on LoadInitState

### ISSUE THREAD

**Issue by thomasjpfan** [dnouri/skorch#392]
The goal of `LoadInitState` is to allow the following script to repeatedly run without modification to continue training:

```python
train_end_cp = TrainEndCheckpoint(dirname="exp1")
load_init = LoadInitState(train_end_cp)
net = NeuralNet(..., callbacks=[train_end_cp, load_init])
net.fit(X, y)
```

I have been wondering if adding `raise_if_error` to `load_params` would be better:

```python
train_end_cp = TrainEndCheckpoint(dirname="exp1")
net = NeuralNet(..., callbacks=[train_end_cp])

net.initialize()
net.load_params(checkpoint=train_end_cp, raise_if_error=False)
net.partial_fit(X, y)
```

**Comment by benjamin-work** [comment]
> The goal of `LoadInitState` is to allow the following script to repeatedly run without modification to continue training:

Could you explain what needs to change for this? I made a quick check and this worked for me as expected (i.e. training continued from where it left off), I didn't see any error.

**Comment by thomasjpfan** [comment]
The first snippet already works, no changes needed.

I want to see what you guys think of the second approach for doing the same thing. Most likely there is nothing wrong with the first snippet and this is a non-issue.

**Comment by ottonemo** [comment]
I think I get what you mean. If there is no checkpoint yet, `load_params` would fail. Adding a flag to ignore the error would allow to use less code for both situations.

I dislike the proposal since it doesn't convey the meaning of the code as the `LoadInitState` variant does. The latter makes it clear what is happening and why. The former adds a dubious flag for ignoring errors where the intention is not clear at all.

Before we search for alternatives to the `LoadInitState` callback I'd rather gather reasons for its existence and identify possible shortcomings. One thing that justifies the existence of `LoadInitState` is, for example, that it is quite easy to accidentally re-initialize the network upon setting parameters. If there was a way to 'safely' re-initialize parameters, loading an initial state upon every `fit` would not be necessary. Any other reasons?

**Comment by thomasjpfan** [comment]
@ottonemo You make good points. After some more thought, I do not think my proposal is better than the current approach. I was trying to search for alternatives to see if there was an approach with a better API design.

Given everyones feedback, the current design with `LoadInitState` looks pretty good.
