### ISSUE TITLE
LOOCV for Transfer Learning using Skorch

### ISSUE THREAD

**Issue by monajalal** [dnouri/skorch#393]
First and foremost, thanks a lot for the amazing "transfer learning" tutorial in Skorch. 

Can you please guide how to apply leave-one-out cross-validation to this tutorial? 
https://github.com/dnouri/skorch/blob/master/notebooks/Transfer_Learning.ipynb

**Comment by benjamin-work** [comment]
In *most cases* skorch should already work with [LOO](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.LeaveOneOut.html).

Here is a minimal code example:

```
import numpy as np
from skorch import NeuralNetClassifier
from skorch.toy import make_classifier
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_classification

X, y = make_classification()
X = X.astype(np.float32)

# when using CV, make sure to set train_split=None to prevent internal train/valid split
# also, set verbose=0 to prevent excessively printing logs
net = NeuralNetClassifier(make_classifier(), verbose=0, train_split=None)
scores = cross_val_score(net, X, y, cv=LeaveOneOut(), scoring='accuracy')
print(np.mean(scores))
```

That being said, in the mentioned notebook, a `Dataset` is used for `X`. This doesn't combine well with sklearn, which will try to split the dataset and make a mess. It is thus easier to make this work if your input data is e.g. a numpy array or torch tensor (or dictionary with the help of [`SliceDict`](https://skorch.readthedocs.io/en/stable/user/helper.html#slicedict)).

That also being said, I would not recommend using LOO for the given problem since this will result in 1 split -> 1 training for each sample, which takes far too long. How about making a manual train/validation split, train the model and optimize hyperparameters based on the internal split, and when finished testing on the validation data?

**Comment by benjamin-work** [comment]
@monajalal Was your issue solved?

**Comment by ottonemo** [comment]
Closing this since the question got answered.
