### ISSUE TITLE
Python 2.7 : yield can't return because "import"

### ISSUE THREAD

**Issue by ismael001** [dnouri/skorch#395]
https://github.com/dnouri/skorch/blob/cd5b411e365004b2182499894c74f983577415eb/skorch/net.py#L348

**Comment by githubnemo** [comment]
Thanks for reporting an issue. 

Unfortunately, we don't support python 2.7 which is why there are errors when using skorch with python 2.7. We have https://github.com/dnouri/skorch/issues/115 to gather reasons for supporting such an old python version since it is considerable effort to backport and maintain. As long as this is not settled we won't fix python 2.7 specific issues.

**Comment by ismael001** [comment]
Ok I try with Python 3.
Thanks for responding 👍
