### ISSUE TITLE
Regarding active maintainers

### ISSUE THREAD

**Issue by thomasjpfan** [dnouri/skorch#416]
I just noticed that @benjamin-work has a "This account is no longer in use." message in his profile. I am concerned with the project maintenance, since @benjamin-work has been active in pushing `skorch` forward.

It looks like @ottonemo, @BenjaminBossan, and @dnouri are the active maintainers for this project. Is this correct?

**Comment by BenjaminBossan** [comment]
I no longer use @benjamin-work but still plan to maintain the project with the others. It's just been a little quiet because of the holidays.

**Comment by thomasjpfan** [comment]
I did not realize that you were the same person 😅. It is good to hear you are still onboard!

**Comment by ottonemo** [comment]
Thanks for watching out!

We are quite concerned about the future of skorch. Should it be the case that one of the core maintainers is quitting the project and/or the project is in danger of dying due to lack of maintenance we will see to it that the community is able to continue the project on its own.

I'm closing this issue but if there is a need to discuss maintenance plans or something similar feel free to open another issue.

**Comment by BenjaminBossan** [comment]
> We are quite concerned about the future of skorch

I believe what you wanted to say is "the future of skorch is important to us" and not "we worry about the future of skorch" :)
